name: Saludo usando secretos
run-name: Ejercicio de secretos
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Jueves!
  SALUDO: Hola
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Hoy es ${{ env.DIA_DE_SEMANA }}"
  saludo-secretos:
      runs-on: ubuntu-latest
      steps:
      - name: Saludar secretos
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Tu contraseña es ${{ secrets.CONTRASENA }}"
