name: Triggers
run-name: ¡Estoy aprendiendo a usar diferentes Triggers!
on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"    
    
