name: Saludo usando variables
run-name: Ejercicio de variables
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Jueves
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Rafles
